services:
  app:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    stdin_open: true  
    tty: true         
    command: sh       
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]